config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get '/mypage', to: 'users#index'
  get 'mypage/sell', to: 'users#sell'


  devise_for :users
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User"
  mount_uploader :image_name, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :price, :image, :image_name, :seller_id, :buyer_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @msg = 'this is a sample page.'
    @users = User.all
    @items = Item.all
  end


private



  def item_params
    params.require(:user).permit(:email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :sell]

  def index

  end

  def sell

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :item_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :item_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :item_price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :item_image %>
  </div>

  <div class="field">
    <%= form.label :image_name %>
    <%= form.file_field :image_name %>
  </div>

  <div class="field">
    <%= form.label :seller_id %>
    <%= form.number_field :seller_id, id: :item_seller_id %>
  </div>

  <div class="field">
    <%= form.label :buyer_id %>
    <%= form.number_field :buyer_id, id: :item_buyer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Image</th>
      <th>Image name</th>
      <th>Seller</th>
      <th>Buyer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td><%= item.image %></td>
      <% if item.image_name? %>
    　  <td><%=  image_tag item.image_name.url%></td>
    　<% else %>
    　  <td>NO image</td>
    　<% end %>
        <td><%= item.seller_id %></td>
        <td><%= item.buyer_id %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @item.image %>
</p>

<p>
  <strong>Image name:</strong>
  <%= @item.image_name %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @item.seller_id %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @item.buyer_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edopen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
    <h1><%= link_to "Edopen" .html_safe, root_path %></h1>

    <% if user_signed_in? %>
      Logged in as <%= current_user.email %>
      <%= link_to "マイページ" .html_safe, mypage_path %>
      <%= link_to "ログアウト" .html_safe, destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "新規登録" .html_safe, new_user_registration_path %>
      <%= link_to "ログイン" .html_safe, new_user_session_path %>
    <% end %>
    </div>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class = "container">
<div class="all-users row">
  <% @users.each do |u| %>
    <div class="user col-lg-3">
      <p><%= u.email %>先生</p>
    </div>
  <% end %>
</div>
<hr>
<div class="all-items row">
  <% @items.each do |i| %>
    <div class="item col-lg-3">
      <p><%= i.name %></p>
      <p><%= i.price %></p>
      <p><%= i.description %></p>
    </div>
  <% end %>
</div>
<hr>
</div>

app/views/users/index.html.erb
<div class="container">
  <p><%= current_user.email %></p>
  <%= link_to "出品する" .html_safe, mypage_sell_path %>
</div>

app/views/users/sell.html.erb
<div class="container">
  <p>this is sample page </p>
</div>